### PR TITLE
ASM-7757 [security] Mask MS-SQL passwords in UI

### PR DESCRIPTION
**Pull request by hribab**
Password fields are typed as strings, changing it
to type "PASSWORD" in order to mask the them in UI

### CODE REVIEW

**Comment by gavin-scott** [comment]
@sushilrai  are you having success with this change?

**Comment by gavin-scott** [comment]
Holding this until we have some confirmation of end-to-end success with this change...

**Comment by hribab** [comment]
Had successful end to end deployment

**Comment by sushilrai** [comment]
I didn't had success with these changes, Encrypted passed is sent in the manifest file and there is additional "decrypt" parameter in the manifest file which is not included in MS SQL Server 2012 init.pp file

**Pull request merged**
